# Generated by Django 4.2.7 on 2023-12-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
